### ISSUE TITLE
wsl --set-default-version 2

### ISSUE THREAD

**Issue by ali27-74** [github/codespaces-jupyter#587]
```[tasklist]
### Tasks
- [ ] https://github.com/github/codespaces-jupyter/pull/582
```

```[tasklist]
### Tasks
- [ ] https://github.com/github/codespaces-jupyter/pull/582
- [ ] https://github.com/github/codespaces-jupyter/pull/542
- [ ] https://github.com/github/codespaces-jupyter/issues/584
- [ ] https://github.com/github/codespaces-jupyter/issues/585
```

**Comment by ali27-74** [comment]
[Uploading ivpn_ivpn.net_b380c2.json…]()
